<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="description" content="<?= $page_desc?>">
    <meta name="keywords" content="<?= $page_keywords?>">
    <meta name="author" content="Sergey Pimenov (olton)">

    <link rel='shortcut icon' type='image/x-icon' href='favicon.ico' />
    
    <title><?= $page_title?></title>

    <link href="/css/metro.min.css" rel="stylesheet">
    <link href="/css/metro-icons.min.css" rel="stylesheet">
    <link href="/css/metro-schemes.min.css" rel="stylesheet">
    <link href="/css/metro-responsive.min.css" rel="stylesheet">

    <link href="/css/app.css" rel="stylesheet">

    <script>
        METRO_CURRENT_LOCALE = 'ru';
        METRO_CALENDAR_WEEK_START = 1;
    </script>

    <script src="/js/jquery-2.1.4.min.js"></script>
    <script src="/js/metro.min.js"></script>
    <script src="/js/app.js"></script>

</head>
<body>
